// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S8k_u-RT53YXCcRkef_Ggs6nhB520T0',
    appId: '1:1039176332601:android:946049f2c784be10f7e4e8',
    messagingSenderId: '1039176332601',
    projectId: 'otp-auth-48162',
    databaseURL: 'https://otp-auth-48162-default-rtdb.firebaseio.com',
    storageBucket: 'otp-auth-48162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE7YBMQ0p9kG6nFoApDIZoOg-UonjVIh8',
    appId: '1:1039176332601:ios:4a79340806941e1cf7e4e8',
    messagingSenderId: '1039176332601',
    projectId: 'otp-auth-48162',
    databaseURL: 'https://otp-auth-48162-default-rtdb.firebaseio.com',
    storageBucket: 'otp-auth-48162.appspot.com',
    iosClientId: '1039176332601-qquke20lqftflgl6rk2fnd6nssql34is.apps.googleusercontent.com',
    iosBundleId: 'com.example.ownerFront',
  );
}
